"""Add resume analysis and application timeline

Revision ID: 937a7ce831c6
Revises: e4b3590c027e
Create Date: 2026-07-03 13:15:24.873944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937a7ce831c6'
down_revision: Union[str, Sequence[str], None] = 'e4b3590c027e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_timelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_timelines_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_timelines_id'), ['id'], unique=False)

    op.create_table('resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('certificates', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_resume_id'), ['resume_id'], unique=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('application_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recruiter_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recruiter_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resume_version_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('expected_salary', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('offer_amount', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('joining_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_application_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_current_stage'), ['current_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_favorite'), ['favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_job_role'), ['job_role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_job_role'))
        batch_op.drop_index(batch_op.f('ix_application_favorite'))
        batch_op.drop_index(batch_op.f('ix_application_current_stage'))
        batch_op.drop_index(batch_op.f('ix_application_archived'))
        batch_op.alter_column('source',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('archived')
        batch_op.drop_column('favorite')
        batch_op.drop_column('joining_date')
        batch_op.drop_column('offer_amount')
        batch_op.drop_column('expected_salary')
        batch_op.drop_column('priority')
        batch_op.drop_column('resume_version_used')
        batch_op.drop_column('recruiter_email')
        batch_op.drop_column('recruiter_name')
        batch_op.drop_column('application_url')
        batch_op.drop_column('job_description')
        batch_op.drop_column('employment_type')

    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_analyses_resume_id'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_id'))

    op.drop_table('resume_analyses')
    with op.batch_alter_table('application_timelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_timelines_id'))
        batch_op.drop_index(batch_op.f('ix_application_timelines_application_id'))

    op.drop_table('application_timelines')
    # ### end Alembic commands ###
