"""Add ChatSession and ChatMessage models

Revision ID: df55cfbe3a14
Revises: a04b0a136d55
Create Date: 2026-07-16 19:20:34.425342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df55cfbe3a14'
down_revision: Union[str, Sequence[str], None] = 'a04b0a136d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatsession_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatsession_user_id'), ['user_id'], unique=False)

    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chatsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessage_session_id'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_id'))

    op.drop_table('chatmessage')
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatsession_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatsession_id'))

    op.drop_table('chatsession')
    # ### end Alembic commands ###
