class ResponseFormatter:
    """
    Formatting and cleansing utility for raw text generated by the AI model.
    """
    @staticmethod
    def format_response(raw_text: str) -> str:
        """
        Cleans up raw response content from Gemini (strips margins, ensures fallback on empty/None outputs).
        """
        if not raw_text:
            return "I apologize, but I was unable to generate a response. Please try asking again."
        
        cleaned = raw_text.strip()
        if not cleaned:
            return "I apologize, but I was unable to generate a response. Please try asking again."
            
        return cleaned
